### ISSUE TITLE
Corpus.nextUrn and Corpus.prevUrn don't work correctly, BUT…

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#103]
... see the pull-request. Changed ~~ to >= in prev and next functions for the Corpus object. Added tests for that in CorpusPrevNextSpec.

**Comment by neelsmith** [comment]
Is it possible to describe and document this in the issue tracker rather than a pull request?

**Comment by Eumaeus** [comment]
In `Corpus.scala`…

Replaced `~~` with `>=` at lines: 663, 669, 692, and 699.

Added 6 texts in `CorpusPrevNextSpec.scala`.

**Comment by neelsmith** [comment]
What is the issue, though?  Anything more concrete than "not correct"?

**Comment by Eumaeus** [comment]
Asking for `corpus.prevUrn(CtsUrn("urn:cts:greekLit:tlg0012.tlg001.perseus_grc2:2.1"))` returns:

`Some(urn:cts:greekLit:tlg0012.tlg001.perseus_grc2:1.596-1.611)`

Asking for `corpus.nextUrn(CtsUrn("urn:cts:greekLit:tlg0012.tlg001.perseus_grc2:2.1"))` returns:

`Some(urn:cts:greekLit:tlg0012.tlg001.perseus_grc2.lemmata:2.2.1-2.4.3)`

**Comment by Eumaeus** [comment]
Fixed and tested.
