### ISSUE TITLE
CorpusChunking

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#130]
Useful both for analysis and presentation…

Given a corpus, chunk it into a Vector[Corpus] according to:
- distinct texts
- citation values (with a @groupLevel param)
    - groupLevel = 1 would give a Vector[Corpus] with 1 citable node in each… not so useful
    - groupLevel = 2 would give a Vector[Corpus] of 24 Corpora for the Iliad, e.g.

**Comment by Eumaeus** [comment]
Implemented in 10.13.0.

Param @levelsToGroup. If you have, e.g., and Iliad, you do @levelsToGroup=1, and you will get 24 Corpus-objects. If you have a tokenized Iliad, you would want to do @levelsToGroup=2, to get 24 Corpus-objects, one for each book, with the lines and their tokens included.

**Comment by neelsmith** [comment]
Closing since this has been merged into master.
