### ISSUE TITLE
Overload the getNgram functions to work on the corpus or a URN

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#34]
In the ScalaJS app, I overloaded getNGram and getUrnsForNgram to work either on the defined corpus, or on a (new) Corpus defined by a URN param. That belongs in the library, probably,

**Comment by neelsmith** [comment]
why not just

    (corpus ~~ URN).urnsForNGram(gram,threshhold,dropPunctuation)

or whatever? 

Part of the point of URN twiddling is that it's composable: you can chain twiddle filters, and you always have a new corpus

I'm going to reject the suggestion and close this for now.  If you want to reopen, give me a use case where chaining  twiddled corpora is undesirable.
