### ISSUE TITLE
URN twiddle on the notional-work level, with a range… unexpected results

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#35]
In our million.tsv corpus…

urn:cts:greekLit:tlg0016.tlg001:1.0-1.1

Results in all of Hdt. in Greek, followed by the requested two nodes of Hdt. in English.

The ScalaJS code producing this result is:

`val tempCorpus: Corpus = corpus ~~ urn`

**Comment by neelsmith** [comment]
implemented and tested
