### ISSUE TITLE
Punctuation still sneaking through in Ngrams

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#40]
Reproduce in scalajscts by doing an Ngram query on the default corpus, with the following params:

` threshold = 100; ignore-punctuation = true; filtered-by = ''; queried on urn:cts:greekLit:tlg0016.tlg001:`

**Comment by neelsmith** [comment]
what value for n, and where should I see an invalid punctuation charcater?

**Comment by neelsmith** [comment]
This happens only in the js compilation, whether because of a bad mapping of jvm data type to js data type or impoverished model of native js strings.

Solution: use JVM to list all characaters in Unicode Punctuation class, and paste into a big ass list we can filter for manually.  Sigh.

**Comment by neelsmith** [comment]
"""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""

is out put of

    val punctList = ArrayBuffer[Char]()
    val punctRE = """[\p{Punct}]""".r

    for (c <- 1 to max) {
      c.toChar match {
        case punctRE() => punctList += c.toChar
        case  _ =>
      }
    }
    println(punctList.mkString)

**Comment by Eumaeus** [comment]
It might be worth adding a test for whitespace-delimited punctuation. I am *not* seeing any problems with normal texts, only with texts where punctuation stands alone as ws-delimited tokens.

**Comment by Eumaeus** [comment]
I de-tokenized punctuation in the two Hdt texts in `million.cex`, and NGrams now work as expected, both when igoring and when not ignoring punctuation.

**Comment by neelsmith** [comment]
Fixed and tested in both jvm and js side.
