### ISSUE TITLE
kwic method on corpus-object: corpus.kwic(CtsUrn, String)

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#43]
In practice, I think we will want to do 'kwic' on a Corpus, handing in a URN and a string, not on a CitableNode.

**Comment by neelsmith** [comment]
I have no idea what that should produce.  A Vector of kwic displayed citable nodes?
I which case, why not just corpus.map(_.kwic("x")) ?

**Comment by neelsmith** [comment]
I think "display" functions belong on passages, not a corpus object. Closing.
