### ISSUE TITLE
TextRepository.label( urn ) should return the passage-component, if present 

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#44]
.label gives the labeling for the bibliographic elements of the URN. If there is a passage component on the URN, that should be included.

**Comment by neelsmith** [comment]
This is not the behavior I observe in the unit tests I'm running....

can you provide a failing example?

**Comment by Eumaeus** [comment]
In the ScalaJS app, this code:

`println(s"${ngurn} yields label ${O2Model.textRepository.catalog.label(ngurn)}")`

yields, e.g.

~~~
[Log] urn:cts:latinLit:phi0474.phi052.omar:11.13.4 yields label M. Tullius Cicero, Epistulae Ad Atticum 
[Log] urn:cts:latinLit:phi0474.phi052.omar:11.16.1 yields label M. Tullius Cicero, Epistulae Ad Atticum 
[Log] urn:cts:latinLit:phi0474.phi052.omar:11.16.2 yields label M. Tullius Cicero, Epistulae Ad Atticum 
[Log] urn:cts:latinLit:phi0474.phi052.omar:11.17A.3 yields label M. Tullius Cicero, Epistulae Ad Atticum 
~~~

**Comment by neelsmith** [comment]
As it should: you're invoking the *catalog*'s label function.  Change you code to 

`O2Model.textRepository.label(ngurn)`

and see what happens.

Closing:  reopen if this is not what you were looking for.
