### ISSUE TITLE
Corpus.findTokens and Corpus.findTokensWithin need ignorePunctuation

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#48]
Testing on Vector("Gyges","Ardys") fails, because the text has "Ardys the son of Gyges,"

This is absolutely correct according to the documentation, which specifies white space as a delimiter, but it will confuse people.

**Comment by neelsmith** [comment]
This needs a more serious design review to consider how best to organize a Corpus DSL.

**Comment by neelsmith** [comment]
Moving this to new milestone for DSL redesign

**Comment by neelsmith** [comment]
Implemented, including new short-hand functions `findWSTokens` that matches on "white-space delimited" tokenization and `findWordTokens` that matches on "word" tokens (white-space delimited, ignoring punctuation)
