### ISSUE TITLE
version-level-urn+passage >> work-level-urn+passage

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#49]
I find myself implementing this in the CiteApp, e.g.:

urn:cts:greekLit:tlg0016.tlg001.loebgrc:1.1 >> urn:cts:greekLit:tlg0016.tlg001:1.1

This seems like a library-thing.

(Reason for doing this: Corpus.nextUrn and Corpus.prevUrn are working from real data, so they will always return a version-level URN. If you've started browsing at the work-level, to keep doing so via navigation, you need to drop the version-ID from the prev- and next-Urns you get back from the Corpus object.)

**Comment by neelsmith** [comment]
Yes: I've filed an issue in `xcite` to enhance CtsUrns with a `dropVersion`function.

Then `dropVersion` on a Corpus could be implemented as corpus.filter(_.dropVersion) which is both simple and tidily parallel to other examples of parallel functions in xcite and ohco2.

**Comment by neelsmith** [comment]
done
