### ISSUE TITLE
Corpus.prevUrn and Corpus.nextUrn… better/different handling of work-level URNs?

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#50]
Observation:

- Create a non-range, leaf-node URN (`urn`) at the work-level, for some work that is represented by two Versions in the corpus (e.g. our Herodotus). This yields two Nodes.
- `Corpus.nextUrn(urn)` will see those two Nodes, and return a URN for the next two nodes.
- It will currently return a two-node Range URN at the Version level (whichever Version is second in sequence, in the Corpus).
- So you have two Nodes, at the Version level. If you then delete the Version-id, and ask for `.nextUrn`, you get *four* nodes, at the Version level.

Better behavior:

I don't know… this probably has many complications. But we should think about it.

**Comment by Eumaeus** [comment]
Or maybe this is okay. Maybe navigation should only happen on real texts, and everything else done via the Catalog. I'm going to leave this open, but I now don't think it needs any changes.

**Comment by neelsmith** [comment]
I think your read is correct.  If you want to navigate, you can *only* do that with reference to a real version.  Whether we want UI stuff that tries to cleverly display all while navigating by one is probably outside the ohco2 library.  Closing for now.
