### ISSUE TITLE
CitedWorks should be ordered according to the Catalog

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#70]
elements in corpus.citedWorks are currently ordered according to their appearance in the loooong list of citable nodes. Reordering works, say, in a display of Cited Works, is harder than it could be.

(This is a total nit-pick, I know, but it would make things easier for app-builders.)

**Comment by neelsmith** [comment]
You're confusing components.

- catalog and corpus exist independently of one another.  citeWorks on a Corpus therefore *cannot* be ordered in terms of a catalog.
- textrepository brings them together.  Is there something different that should be done, or a different function for listed works in a textrepository?  


Changing this from enhancement to question label.

**Comment by neelsmith** [comment]
Further note why this may not even be a question;  TextRepository enforces a 1<->1 correspondence of works cataloged as online and works cited in the corpus.  Therefore you can just use the textrepository's catalog to get them in catalog sequence.  In short, if you have a TextRepository (and not just a corpus) i don't see why you would ever need/use the corpus function citedWorks.

I don't think there's an issue here, but I'm not closing until I iunderstand the intention of the question better.

**Comment by neelsmith** [comment]
Having heard no objections... I'm going to go ahead and close this out.  We can reopen it if I'm misunderstood the original question, and these comments don't address the question adequately.
