### ISSUE TITLE
ngramHisto fails on big data

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#81]
`java.lang.OutOfMemoryError: GC overhead limit exceeded`

In SBT Console, did `corpus.ngramHisto(3,5,true)` on a corpus of 87k nodes.

Reproduce by checking out <https://github.com/Eumaeus/croala-twiddle> and doing:

- `sbt console`
- `:load loadcroala.sc`
- `corpus.ngramHisto(3,5,true)`

Perhaps worth testing on corpora of increasing size… is this some kind of non-polynomial-time thing?

(I'm trying again on a reset sbt console, to see if my earlier work had used up too much memory.)

**Comment by neelsmith** [comment]
also possible that instances of tail recursion are not taking advantage of scala annotations to optimize chances of avoiding stacking overflow

**Comment by Eumaeus** [comment]
I just tested this on a corpus of 200k nodes, and it returned results instantly. Closing this for now.
