### ISSUE TITLE
Convenience method: printCorpus

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#82]
For my Split demo, I define this in my `loadcroala.sc` file, for use in SBT Console:

`def printCorpus(c:Corpus) = for (cn <- c.nodes) println(s"${cn.urn}\t ${cn.text}")`

In the long term, it might save a lot of time?

**Comment by neelsmith** [comment]
I don't think we should have have functions directly printing as their primary action.  

1. They're necessarily of type Unit and therefore impossible to test propertly
2. If you instead produce output that can be directly printed (e.g., override `toString` or add a convenience function such as `printableString`), you have a testable function

I *would* like to see a `toCex` function.  But I'm don't see the use case for this. What is the application for a generating string values of a corpus like this?

**Comment by Eumaeus** [comment]
Makes sense. This was just for newbies working in SBT console for the first time, for instant feedback upon making a repository. Easy enough to define stuff like this in a script.
