### ISSUE TITLE
~~ operation gives bad results when there is a Version and derived Exemplars

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#98]
See Branch "TwiddleFilterProblems" for a new test suite that demonstrates the problem.

**Comment by neelsmith** [comment]
This is correct OR'ing behavior, AFAICS.  Will look closely at all examples, but I think the issue here is lack of good documentation

**Comment by neelsmith** [comment]
I'm closing this issue, for now at least, since I believe it is covered by the more fully specified algebra of URN relations that is implemented for CtsUrn and CitableNode.
